language: python
cache: pip
dist: xenial
python:
  - "3.6"
  - "3.7"

before_install:
  - pip install pip --upgrade

install:
  - pip install -e .[tests,notebooks]

script:
  - pytest --cov -r a --cov-report term-missing
  - pytest -rfsxEX --nbval-lax ./notebooks --sanitize ./notebooks/tests_sanitize.cfg

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then codecov; fi
