name: Test PyPI install
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * 3'

jobs:
  test-installation:

    name: Test PyPI install (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: [3.6, 3.7]  # , 3.8]  # cannot include 3.8 because of pyam

    steps:
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set matplotlib backend (${{ runner.os }})
      if: startsWith(runner.os, 'macOS')
      run: |
        mkdir -p ~/.matplotlib
        echo 'backend: TkAgg' >> ~/.matplotlib/matplotlibrc

    - name: Install package
      run: |
        pip install silicone --pre

    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Test installation
      run: |
        python scripts/test_install.py
